const mockResponses = {
  getCatsResponse: {
    status: 200,
    data: [
      {
        breeds: [],
        id: 'b53',
        url: 'https://cdn2.thecatapi.com/images/b53.jpg',
        width: 560,
        height: 373,
      },
      {
        breeds: [],
        id: 'bpi',
        url: 'https://cdn2.thecatapi.com/images/bpi.jpg',
        width: 538,
        height: 717,
      },
    ],
  },
  // (REFACTOR) REDUCE MOCKS PPOPS BASED ON APP USAGE
  getBreedsResponse: {
    status: 200,
    data: [
      {
        weight: {
          imperial: '7  -  10',
          metric: '3 - 5',
        },
        id: 'abys',
        name: 'Abyssinian',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/abyssinian',
        vcahospitals_url: 'https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian',
        temperament: 'Active, Energetic, Independent, Intelligent, Gentle',
        origin: 'Egypt',
        country_codes: 'EG',
        country_code: 'EG',
        description: 'The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.',
        life_span: '14 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 1,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_(cat)',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '8 - 13',
          metric: '4 - 6',
        },
        id: 'cymr',
        name: 'Cymric',
        vetstreet_url: 'http://www.vetstreet.com/cats/cymric',
        temperament: 'Gentle, Loyal, Intelligent, Playful',
        origin: 'Canada',
        country_codes: 'CA',
        country_code: 'CA',
        description: 'The Cymric is a placid, sweet cat. They do not get too upset about anything that happens in their world. They are loving companions and adore people. They are smart and dexterous, capable of using his paws to get into cabinets or to open doors.',
        life_span: '8 - 14',
        indoor: 0,
        lap: 1,
        alt_names: 'Spangle',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Cymric_(cat)',
        hypoallergenic: 0,
      },
    ],
  },
  getFavouritesResponse: {
    status: 200,
    data: [
      {
        created_at: '2019-10-12T11:52:35.000Z',
        id: '2008125',
        image: {
          id: '3Wjx1Tq7X',
          url: 'https://cdn2.thecatapi.com/images/3Wjx1Tq7X.jpg',
        },
        image_id: '3Wjx1Tq7X',
        sub_id: 'vissarion',
        user_id: 'x2ulwa',
      },
      {
        created_at: '2019-10-12T11:52:37.000Z',
        id: '2008126',
        image: {
          id: 'p2U4ZXgKL',
          url: 'https://cdn2.thecatapi.com/images/p2U4ZXgKL.jpg',
        },
        image_id: 'p2U4ZXgKL',
        sub_id: 'vissarion',
        user_id: 'x2ulwa',
      },
    ],
  },
  saveFavouriteResponse: {
    status: 200,
    data: {
      id: 2008053,
      message: 'SUCCESS',
    },
  },
  deleteFavouriteResponse: {
    status: 200,
    data: {
      message: 'SUCCESS',
    },
  },
};

export default mockResponses;
