// Action types for cat lovers application
export const REQUEST_RANDOM_CATS = 'REQUEST_RANDOM_CATS';
export const SET_RANDOM_CATS = 'SET_RANDOM_CATS';
export const REQUEST_BREEDS = 'REQUEST_BREEDS';
export const SET_BREEDS = 'SET_BREEDS';
export const SET_UI_STATE = 'SET_UI_STATE';
export const REQUEST_BY_BREED = 'REQUEST_BY_BREED';
export const SET_BREED_BY_ID = 'SET_BREED_BY_ID';
export const SUBMIT_IMAGE_AS_FAVORITE = 'SUBMIT_IMAGE_AS_FAVORITE';
export const DELETE_IMAGE_FROM_FAVORITE = 'DELETE_IMAGE_FROM_FAVORITE';
export const REQUEST_FAVORITES = 'REQUEST_FAVORITES';
export const SET_FAVORITES_CATS = 'SET_FAVORITES_CATS';
export const APPEND_RANDOM_CATS = 'APPEND_RANDOM_CATS';
export const CLEAR_BY_BREED = 'CLEAR_BY_BREED';